"""
Concatenate all project source files into a single Markdown bundle for
external code review.

Usage (from repo root):
    python scripts/bundle_for_review.py
    npm run export:review

Writes Markdown bundles at the repo root (same content in both):

  CODE_REVIEW_SINGLE_FILE.md — primary name for "one file for review"
  CODE_REVIEW_BUNDLE.md — alias kept for backwards compatibility

Share either file, or zip the repo excluding node_modules/.venv (see .gitignore)
if reviewers need the tree.

Skips vendored / generated / secret files:
    node_modules, .venv, .git, __pycache__, dist, build, .next, .pytest_cache
    storage/, data/, output/, frontend/dist, frontend/.vite
    binary assets (png, svg, ico, pdf, xlsx, sqlite, woff, woff2, ttf, zip)
    .env (but includes .env.example)
    package-lock.json, pnpm-lock.yaml, yarn.lock
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_OUT_PRIMARY = ROOT / "CODE_REVIEW_SINGLE_FILE.md"
_OUT_ALIAS = ROOT / "CODE_REVIEW_BUNDLE.md"

# Directory names that mark an entire subtree as skipped.
SKIP_DIRS = {
    "node_modules",
    ".venv",
    ".git",
    "__pycache__",
    ".pytest_cache",
    "dist",
    "build",
    ".next",
    "storage",
    "data",
    "output",
    "input",
    ".vite",
    ".cache",
    ".turbo",
}

# File extensions we never inline (binary or generated).
SKIP_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico",
    ".svg",                # usually XML but often large / generated
    ".pdf", ".xlsx", ".xls", ".xlsm", ".doc", ".docx",
    ".sqlite", ".db", ".sqlite3",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".zip", ".tar", ".gz", ".7z",
    ".pyc", ".pyo", ".so", ".dll", ".exe",
    ".mp4", ".mov", ".mp3", ".wav",
}

# Explicit filenames to skip anywhere in the tree.
SKIP_FILES = {
    ".env",                  # secrets
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "CODE_REVIEW_BUNDLE.md",  # don't include generated bundle(s)
    "CODE_REVIEW_SINGLE_FILE.md",
    "t.txt",                 # scratch file
}

# Map extensions to Markdown code-fence languages.
LANG_BY_EXT = {
    ".py": "python",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".js": "javascript",
    ".cjs": "javascript",
    ".mjs": "javascript",
    ".jsx": "jsx",
    ".json": "json",
    ".html": "html",
    ".css": "css",
    ".md": "markdown",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "ini",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".sh": "bash",
    ".ps1": "powershell",
    ".bat": "bat",
    ".env.example": "ini",
}


def should_skip(path: Path) -> bool:
    parts = set(path.parts)
    if parts & SKIP_DIRS:
        return True
    if path.name in SKIP_FILES:
        return True
    if path.suffix.lower() in SKIP_EXTS:
        return True
    return False


def fence_language(path: Path) -> str:
    if path.name == ".env.example":
        return "ini"
    return LANG_BY_EXT.get(path.suffix.lower(), "")


def iter_files(root: Path):
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        if should_skip(p.relative_to(root)):
            continue
        # Read a small sample to detect binary-by-null-byte
        try:
            with p.open("rb") as f:
                chunk = f.read(8192)
            if b"\x00" in chunk:
                continue
        except OSError:
            continue
        yield p


def main() -> int:
    from datetime import datetime, timezone

    files = list(iter_files(ROOT))
    tz = datetime.now(timezone.utc).astimezone()
    stamped = tz.strftime("%Y-%m-%d %H:%M:%S %z")

    lines: list[str] = []
    lines.append("# mdhhs-poc-builder — single-file code export\n\n")
    lines.append(
        "_Generated by `scripts/bundle_for_review.py` (`npm run export:review`)._\n\n"
    )
    lines.append(
        "_Monorepo source bundle for human review. Excludes vendored or generated trees, "
        "binary assets, `node_modules`, `.venv`, `.env`, and prior export files._\n\n"
    )
    lines.append(f"**Generated:** {stamped}\n\n")
    lines.append("---\n\n")
    lines.append("## Table of contents\n\n")
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        anchor = rel.replace("/", "").replace(".", "").replace("_", "").lower()
        lines.append(f"- [{rel}](#{anchor})\n")
    lines.append("\n---\n\n")

    total_bytes = 0
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        try:
            text = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = p.read_text(encoding="latin-1")
        total_bytes += len(text.encode("utf-8"))
        lang = fence_language(p)
        lines.append(f"## `{rel}`\n\n")
        lines.append(f"```{lang}\n")
        safe = text.replace("```", "``\u200b`")
        lines.append(safe)
        if not safe.endswith("\n"):
            lines.append("\n")
        lines.append("```\n\n")

    body_text = "".join(lines)
    for out_path in (_OUT_PRIMARY, _OUT_ALIAS):
        out_path.write_text(body_text, encoding="utf-8", newline="\n")
        print(
            f"wrote {out_path.relative_to(ROOT)} — {len(files)} files, "
            f"{total_bytes:,} bytes of source text"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
