/**
 * Schedule-related constants and day-of-week helpers.
 *
 * Placement-authority rule (IMPORTANT):
 *   The single source of truth for *which weekdays a task runs on* is the
 *   `ScheduleConfig` that the backend stores on the plan and exposes as
 *   `plan.config.tasks[]`. `dayNamesForFrequency()` below is NOT the
 *   placement engine — it's only a weekend-weighted template we fall back
 *   to on truly legacy plans that predate both the ScheduleConfig editor
 *   and the month-aware schedule (i.e. the backend never persisted either
 *   a config or a concrete weekly pattern for this plan).
 *
 *   When loading a plan into the editor, always follow this order:
 *     1. `plan.config.tasks[name].selected_weekdays` (+ `selected_dates`)
 *     2. `plan.schedule.days[weekday].tasks[]` — the collapsed weekly
 *        projection, still month-specific in spirit since it was
 *        generated by the last calibration.
 *     3. `dayNamesForFrequency(daysPerWeek)` — the legacy fallback.
 *
 *   `selectedWeekdaysForTask()` encapsulates that lookup so the three
 *   editor entry points (`scheduleEditor.ts`, `scheduleBuild.ts`, and
 *   the React editor component) never have to re-implement it.
 */

import type {
  AvailabilityWindowEvaluation,
  Plan,
  WorkerAvailabilityDay,
} from "@/types"
import { formatHoursMinutes } from "./format"

const WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
] as const

/**
 * Legacy-only weekend-weighted placement template.
 *
 * Mirrors backend `calculate.default_weekdays_for_dpw`. This function is
 * **not** the authoritative placement engine — it's the last-resort
 * fallback used when a plan has neither a `ScheduleConfig` nor a saved
 * weekly pattern. Never call this directly from editor load/save logic;
 * use `selectedWeekdaysForTask()` instead, which tries the config and
 * schedule first.
 *
 * Kept here (rather than deleted) because:
 *   - The PDF-upload → schedule path uses it to seed the initial
 *     ScheduleConfig before the editor exists.
 *   - Some legacy plan rows in the DB have neither a `config` nor a
 *     populated `schedule.days` dict; the editor still needs to show
 *     *something* when those open.
 */
export function dayNamesForFrequency(daysPerWeek: number): readonly string[] {
  const d = Math.trunc(Number(daysPerWeek))
  if (d <= 0) return [] as const
  if (d >= 7) return WEEK
  if (d === 1) return ["Sunday"] as const
  if (d === 2) return ["Saturday", "Sunday"] as const
  if (d === 3) return ["Friday", "Saturday", "Sunday"] as const
  if (d === 4) return ["Thursday", "Friday", "Saturday", "Sunday"] as const
  if (d === 5)
    return ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] as const
  if (d === 6)
    return [
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ] as const
  return WEEK
}

/** Kept in sync with ``backend/app/calculate.MIN_WORKER_AVAILABILITY_SPAN_MINUTES``. */
export const MIN_WORKER_AVAILABILITY_SPAN_MINUTES = 120

/**
 * Parse display times ("1:00 PM" / "8:00 PM") to minutes from midnight.
 * Returns null if the string does not match the backend ``_parse_ampm`` shape.
 */
export function parseAmPmToMinutes(s: string): number | null {
  const t = (s || "").trim()
  const m = t.match(/^(\d{1,2}):(\d{2})\s*([AP]M)$/i)
  if (!m) return null
  let h = Number(m[1])
  const mi = Number(m[2])
  const ap = m[3].toUpperCase()
  if (!Number.isFinite(h) || !Number.isFinite(mi) || mi < 0 || mi > 59 || h < 1 || h > 12)
    return null
  const h24 =
    ap === "AM" ? (h === 12 ? 0 : h) : h === 12 ? 12 : h + 12
  return h24 * 60 + mi
}

/**
 * Latest clock-out bound for a calendar day that has scheduled visits —
 * mirrors ``backend/app/calculate.effective_visit_latest_for_worker_day``.
 */
export function effectiveVisitLatestDisplay(
  row: Partial<WorkerAvailabilityDay> | WorkerAvailabilityDay,
): string {
  const baseLatest = (row.latest || "8:00 PM").trim() || "8:00 PM"
  if (!row.visit_day_longer) return baseLatest
  let ext = (row.visit_day_latest || "").trim()
  if (!ext) ext = "10:00 PM"
  const extM = parseAmPmToMinutes(ext)
  const baseM = parseAmPmToMinutes(baseLatest)
  if (extM === null || baseM === null) return ext
  if (extM < baseM) return baseLatest
  return ext
}

/**
 * Evaluate one weekday row for reversed From/To and span vs
 * :const:`MIN_WORKER_AVAILABILITY_SPAN_MINUTES` (visit-day end uses
 * ``visit_day_latest`` when ``visit_day_longer`` is set).
 */
export function evaluateAvailabilityWindow(
  day: Partial<WorkerAvailabilityDay> | WorkerAvailabilityDay,
): AvailabilityWindowEvaluation {
  const earliest = (day.earliest || "1:00 PM").trim() || "1:00 PM"
  const upper = effectiveVisitLatestDisplay(day)
  const e0 = parseAmPmToMinutes(earliest)
  const u0 = parseAmPmToMinutes(upper)
  if (e0 === null || u0 === null) {
    return {
      minutes: 0,
      reversed: false,
      tooNarrow: false,
      note: "Could not parse From / To times",
    }
  }
  const reversed = e0 > u0
  const minutes = reversed ? 0 : u0 - e0
  const MIN = MIN_WORKER_AVAILABILITY_SPAN_MINUTES
  if (reversed) {
    return {
      minutes,
      reversed: true,
      tooNarrow: false,
      note: "Reversed From/To — swap them?",
    }
  }
  const tooNarrow = minutes < MIN
  if (tooNarrow) {
    return {
      minutes,
      reversed: false,
      tooNarrow: true,
      note: `Only ${minutes} min available (need ≥ ${MIN})`,
    }
  }
  return { minutes, reversed: false, tooNarrow: false, note: null }
}

/**
 * Union of weekdays implied by authorized ``days_per_week`` values (same
 * weekend-weighted template as schedule generation).
 */
export function visitWeekdaysUnionFromAuthorizedTasks(
  tasks: readonly { days_per_week: number }[],
): ReadonlySet<string> {
  const s = new Set<string>()
  for (const t of tasks) {
    for (const d of dayNamesForFrequency(t.days_per_week)) s.add(d)
  }
  return s
}

export type AvailabilityPreflightViolation = { day: string; note: string }

/**
 * First weekday that fails preflight: reversed window always; too-narrow
 * only if ``visitWeekdays`` is undefined (any day) or this day is in the set.
 */
export function firstAvailabilityPreflightViolation(
  avail: Record<string, WorkerAvailabilityDay | undefined>,
  options?: { visitWeekdays?: ReadonlySet<string> },
): AvailabilityPreflightViolation | null {
  const visitDays = options?.visitWeekdays
  for (const d of WEEK) {
    const row = avail[d] ?? {}
    const ev = evaluateAvailabilityWindow(row)
    if (ev.note === "Could not parse From / To times")
      return { day: d, note: ev.note }
    if (ev.reversed) return { day: d, note: ev.note ?? "Reversed window" }
    const checkNarrow = visitDays === undefined || visitDays.has(d)
    if (ev.tooNarrow && checkNarrow)
      return { day: d, note: ev.note ?? "Window too narrow" }
  }
  return null
}

// ---------------------------------------------------------------------------
// Config-first placement resolver
// ---------------------------------------------------------------------------

interface ConfigTaskLike {
  task_name?: string
  selected_weekdays?: string[]
}

interface ScheduleDayLike {
  tasks?: string[]
}

interface ConfigLike {
  tasks?: ConfigTaskLike[]
}

interface PlanLike {
  config?: ConfigLike & Record<string, unknown>
  schedule?: { days?: Record<string, ScheduleDayLike> } & Record<string, unknown>
}

/**
 * Resolve the weekdays a given task runs on for this specific plan.
 *
 * Tier 1 — `plan.config.tasks[name].selected_weekdays` (user-edited
 *         ScheduleConfig). This is authoritative and may contain any
 *         subset of weekdays; we return it verbatim even if it's empty.
 * Tier 2 — `plan.schedule.days[weekday].tasks[]` (concrete weekly pattern
 *         from the last calibration). Reflects what the scheduler
 *         actually produced for this month, including any overrides the
 *         editor applied before the ScheduleConfig shape existed.
 * Tier 3 — `dayNamesForFrequency(daysPerWeek)` — the legacy template.
 *
 * `fallbackDaysPerWeek` is only consulted for Tier 3; pass the task's
 * authorized `days_per_week` so the fallback produces a sensible default.
 */
export function selectedWeekdaysForTask(
  plan: Plan | PlanLike | null | undefined,
  taskName: string,
  fallbackDaysPerWeek: number,
): readonly string[] {
  const nm = String(taskName || "").trim()
  if (!nm) return [] as const

  // Tier 1: user-edited ScheduleConfig on the plan.
  const cfg = (plan?.config ?? null) as ConfigLike | null
  const cfgTasks = Array.isArray(cfg?.tasks) ? cfg.tasks : []
  if (cfgTasks.length > 0) {
    const entry = cfgTasks.find(
      (t) => String(t?.task_name ?? "").trim() === nm,
    )
    if (entry && Array.isArray(entry.selected_weekdays)) {
      // Return verbatim — an explicit empty list means "never runs on
      // any weekday by template" (the task may still run on specific
      // dates via `selected_dates`), and callers rely on that.
      return entry.selected_weekdays.slice()
    }
  }

  // Tier 2: collapsed weekly pattern from the saved schedule.
  const dayMap = (plan?.schedule?.days ?? {}) as Record<string, ScheduleDayLike>
  const fromSchedule: string[] = []
  for (const d of WEEK) {
    const list = dayMap[d]?.tasks
    if (Array.isArray(list) && list.includes(nm)) fromSchedule.push(d)
  }
  if (fromSchedule.length > 0) return fromSchedule

  // Tier 3: legacy weekend-weighted fallback.
  return dayNamesForFrequency(fallbackDaysPerWeek)
}

export { WEEK as WEEK_DAYS }

export const DOW_SHORT = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const

export function isWeekendDay(day: string) {
  return day === "Saturday" || day === "Sunday"
}

export function isFridayDay(day: string) {
  return day === "Friday"
}

export function getShortDow(full: string) {
  const i = WEEK.indexOf(full as (typeof WEEK)[number])
  return i >= 0 ? DOW_SHORT[i] : full
}

/** Monday-start: row 0 = Monday, row 1 = Tuesday, ... */
export function longDayForLogRow(rowIndex0: number) {
  return WEEK[rowIndex0 % 7]!
}

/**
 * Check names whose Expected/Actual values are raw-minute integers. When
 * displayExpectedActual is invoked with one of these as ``checkName``, a
 * parenthesised ``"Xh Ym"`` companion is appended so reviewers don't have
 * to mentally divide by 60. Dollar-, count-, and boolean-valued checks
 * stay untouched.
 *
 * Kept in sync with the backend check names emitted by
 * ``backend/app/validate.py``.
 */
/** Strip leading ``3a — ``, ``12) ``, ``1 - `` style numbering from validator check names. */
export function stripLeadingCheckNumber(raw: string): string {
  return raw
    .replace(/^(\d+[a-z]?)\s*[-—.)]\s*/i, "")
    .replace(/^\d+\s*[-—.)]\s*/, "")
    .trim()
}

const MINUTE_VALUED_CHECK_NAMES = new Set<string>([
  "Weekly budget arithmetic",
  "Monthly minutes target",
  "Billable minutes = min(delivered, authorized)",
])

export function displayExpectedActual(v: unknown, checkName?: string): string {
  if (v === null || v === undefined) return "—"
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
    const base = String(v)
    // Decorate integer minute values on the known minute-valued checks.
    if (
      typeof v === "number" &&
      Number.isFinite(v) &&
      checkName &&
      MINUTE_VALUED_CHECK_NAMES.has(stripLeadingCheckNumber(checkName))
    ) {
      return `${base} (${formatHoursMinutes(Math.trunc(v))})`
    }
    return base
  }
  try {
    return JSON.stringify(v)
  } catch {
    return String(v)
  }
}
